### ISSUE TITLE
对输出结果的疑问

### ISSUE THREAD

**Issue by szhnj** [THUYimingLi/BackdoorBox#49]
你好，后门攻击的输出结果的含义有点不明白，输出如何查看攻击成功率呀
![ZWROFIV {EJ91P$C{YDAC S](https://user-images.githubusercontent.com/114074346/191495130-210bef35-8cf8-46e1-898a-cf4516a800b4.png)

**Comment by THUYimingLi** [comment]
> 你好，后门攻击的输出结果的含义有点不明白，输出如何查看攻击成功率呀 ![ZWROFIV {EJ91P$C{YDAC S](https://user-images.githubusercontent.com/114074346/191495130-210bef35-8cf8-46e1-898a-cf4516a800b4.png)

感谢对我们工具箱的关注和使用。'The result on poisoned test dataset' 表示的就是预测被100%投毒的测试数据集时的结果。其中的TOP-1 accuracy就是我们指的ASR。例如，在你的这个例子里，攻击成功率是0.3067 (30.67%).
