### ISSUE TITLE
ModuleNotFoundError: No module named 'curves'

### ISSUE THREAD

**Issue by MinqiShao** [THUYimingLi/BackdoorBox#51]
<img width="383" alt="image" src="https://user-images.githubusercontent.com/79695208/201301291-f8b4307d-8306-49cd-a396-08ddfdd150c8.png">
运行tests的一些example时，在core/models的resnet_curve.py中会报出如上错误。但IDE并没有警告或者报错，只有当运行时才会出现。
请问是否有人遇到该问题？谢谢。

**Comment by THUYimingLi** [comment]
> <img alt="image" width="383" src="https://user-images.githubusercontent.com/79695208/201301291-f8b4307d-8306-49cd-a396-08ddfdd150c8.png">
> 
> 运行tests的一些example时，在core/models的resnet_curve.py中会报出如上错误。但IDE并没有警告或者报错，只有当运行时才会出现。 请问是否有人遇到该问题？谢谢。

感谢对我们工具箱的关注和使用！请问你能提供更多的复现细节么？暂时不太理解你现在是怎么遇到这个error的。（比如，你运行的什么example遇到了这个错误，什么叫IDE没有警告或者报错哈）

**Comment by MinqiShao** [comment]
谢谢回复～
我在pycharm上运行的是test_BadNets.py。在import core时会顺着引用到core/models的resnet_curve.py，运行时引起错误。
静态检查代码时并没有显示no module named 'curves'，并且可以跳转。
<img width="391" alt="image" src="https://user-images.githubusercontent.com/79695208/201316403-ca3295f2-6a4e-4925-ac43-654abfaf6453.png">

**Comment by MinqiShao** [comment]
从test中挪到外面后可以执行成功了。
谢谢你的回复:)
我之后真正使用时会使用命令行。
