### ISSUE TITLE
Emprical study on effect of  `poisoned transform train index` ?

### ISSUE THREAD

**Issue by Oklahomawhore** [THUYimingLi/BackdoorBox#66]
Hi big brother, I'm a graduate student from sjtu doing research on backdoor learning, thank you for the project it is of great help to my study. I've experimented with different timing of injecting backdoor trigger in torchvision transforms previously, and I'm curious that do you have empirical results on the effect of injecting backdoor triggers at different stage of image augmentation?

Thank you very much for your time.

**Comment by THUYimingLi** [comment]
> Hi big brother, I'm a graduate student from sjtu doing research on backdoor learning, thank you for the project it is of great help to my study. I've experimented with different timing of injecting backdoor trigger in torchvision transforms previously, and I'm curious that do you have empirical results on the effect of injecting backdoor triggers at different stage of image augmentation?
> 
> Thank you very much for your time.

Hi, thanks for reaching out and using our toolbox! Could you provide more details about 'at different stage of image augmentation'?

**Comment by Oklahomawhore** [comment]
Sorry for not making it clear! Here is a simplified explanation of my problem, hope it helps!

From image file to network input, there are a number of points we can patch backdoor trigger onto the image
![截屏2024-02-19 22 03 38](https://github.com/THUYimingLi/BackdoorBox/assets/13502612/cc5a8074-5849-4c56-837b-079c3a070006)
Say the train transform includes **RandomHorizontalFlip** and **Normalize**, and the dataset is CIFAR10.

# Image Transformation Pipeline with Trigger Insertion Points

1. **Original Image**
   - The raw image from the CIFAR-10 dataset.

2. **➤ [Point A] Trigger Insertion (Before RandomHorizontalFlip)**
   - At this point, a trigger can be added to the original image *before* applying any augmentation.

3. **➤ RandomHorizontalFlip**
   - Data augmentation step that randomly flips the image horizontally.

4. **➤ [Point B] Trigger Insertion (After RandomHorizontalFlip, Before Normalization)**
   - Here, the trigger can be added *after* the RandomHorizontalFlip but *before* normalization.

5. **➤ Normalization**
   - Standardizing the pixel values of the image.

6. **➤ [Point C] Trigger Insertion (After Normalization)**
   - Finally, a trigger can be added *after* the normalization process.


There are three choice of trigger insertion points, my problem is that is there any difference between them?

**Comment by THUYimingLi** [comment]
> Sorry for not making it clear! Here is a simplified explanation of my problem, hope it helps!
> 
> Say the train transform includes **RandomHorizontalFlip** and **Normalize**, and the dataset is CIFAR10, and the attack method is BadNets. From image file to network input, there are a number of points we can patch backdoor trigger onto the image, ![截屏2024-02-19 22 03 38](https://private-user-images.githubusercontent.com/13502612/305974490-cc5a8074-5849-4c56-837b-079c3a070006.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzODgzODksIm5iZiI6MTcwODM4ODA4OSwicGF0aCI6Ii8xMzUwMjYxMi8zMDU5NzQ0OTAtY2M1YTgwNzQtNTg0OS00YzU2LTgzN2ItMDc5YzNhMDcwMDA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDAwMTQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMTUzN2ZjZTdkMjM0YmE0YTYxYTk1YzAyYjNkNDI2NDIzYjBkN2ExNGUyNGNmZWQ4ZThlMWNjNWU3OWEzNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PlLwpzWyAVgvvC0ZF8SRVq4V43MuewDfTC5MJ_jackg) and we can add the trigger at point A, B or C explained below,
> 
> # Image Transformation Pipeline with Trigger Insertion Points
> 1. **Original Image**
>    
>    * The raw image from the CIFAR-10 dataset.
> 2. **➤ [Point A] Trigger Insertion (Before RandomHorizontalFlip)**
>    
>    * At this point, a trigger can be added to the original image _before_ applying any augmentation.
> 3. **➤ RandomHorizontalFlip**
>    
>    * Data augmentation step that randomly flips the image horizontally.
> 4. **➤ [Point B] Trigger Insertion (After RandomHorizontalFlip, Before Normalization)**
>    
>    * Here, the trigger can be added _after_ the RandomHorizontalFlip but _before_ normalization.
> 5. **➤ Normalization**
>    
>    * Standardizing the pixel values of the image.
> 6. **➤ [Point C] Trigger Insertion (After Normalization)**
>    
>    * Finally, a trigger can be added _after_ the normalization process.
> 
> There are three choice of trigger insertion points, my problem is that is there any difference between them?

I see. This is an interesting question. Although I do not evaluate it comprehensively (I believe there is no paper did it), I have some analyses, as follows.

1. For poison-only backdoor attacks, trigger patterns can be added only at point (a) since the adversaries cannot control the training process.
2. For training-controlled or model-modified attacks, people usually add triggers at point (b) since transformation will change the distribution of 'real' trigger distribution learned by DNNs (notice that only normalization will be used in the inference process!).
3. In general, I think point (a) is hardest and point (b) is easy for attacking DNNs. However, in most cases, I think the choice has only minor effects to the final attack performance since backdoor is a easily learned model short-cut. But in some hard-learning cases (e.g., one-pixel trigger), it may make difference.

**Comment by Oklahomawhore** [comment]
Thank you very much for your great insight, it's of tremendous help!
