### ISSUE TITLE
Bug in WaNET attack

### ISSUE THREAD

**Issue by AcronRK** [THUYimingLi/BackdoorBox#68]
Hi, this is some amazing work and is really helpful for people just starting out. I think I might have found a bug and wanted to let you know.

In attacks -> WaNET.py -> add_trigger(self, img, noise=False)
- If there is noise, the grid is calculated as: grid = self.grid + ins / self.h
- However, in the next line grid is recalculated as: grid = torch.clamp(self.grid + ins / self.h, -1, 1)

Im also attaching an image

![Screenshot 2024-02-24 150651](https://github.com/THUYimingLi/BackdoorBox/assets/56065739/67a56e2c-aecd-4f36-ac4f-750639dcd08f)

**Comment by THUYimingLi** [comment]
> Hi, this is some amazing work and is really helpful for people just starting out. I think I might have found a bug and wanted to let you know.
> 
> In attacks -> WaNET.py -> add_trigger(self, img, noise=False)
> 
> * If there is noise, the grid is calculated as: grid = self.grid + ins / self.h
> * However, in the next line grid is recalculated as: grid = torch.clamp(self.grid + ins / self.h, -1, 1)
> 
> Im also attaching an image
> 
> ![Screenshot 2024-02-24 150651](https://private-user-images.githubusercontent.com/56065739/307527138-67a56e2c-aecd-4f36-ac4f-750639dcd08f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4MjI5ODksIm5iZiI6MTcwODgyMjY4OSwicGF0aCI6Ii81NjA2NTczOS8zMDc1MjcxMzgtNjdhNTZlMmMtYWVjZC00ZjM2LWFjNGYtNzUwNjM5ZGNkMDhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDAwNTgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMmMxNDE4ODZjZDNiZGE0ZmY3ZGJkNGUyMDU3YTUyN2JiMDJkYjljY2UxNGRiOGRmMTQzZDRjOTg3ZDFhOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ubfPhsMepiKNk0QW7vBcuutdLS-ppwdFsMyh-_aNDog)

Hi, AcronRK,

Thanks for using our toolbox and nice words. In general, I would say it is not a bug but a code redundancy. Specifically, the torch.clamp is to ensure that all elements are within [-1, 1]. Unless we have a misunderstanding about the range of grid, it should work well. But as I said, there is a redundancy, I think you can delete the line 'grid = self.grid + ins / self.h' and also run the code with the same results. 

Anyway, thanks for your notification!

**Comment by AcronRK** [comment]
Ah thank you for the clarification :)
