### ISSUE TITLE
hello.  what process i need to follow for creating the badnet backdoor attack using  BackdoorBox? Do i need to download the full codes on my computer use it??

### ISSUE THREAD

**Issue by zsaba** [THUYimingLi/BackdoorBox#73]

**Comment by THUYimingLi** [comment]
you should download all codes, then run the pip install -r requirements.txt to install required packages. You can use codes in the test_BadNets.py to create your attack.

**Comment by zsaba** [comment]
i was going through the SCALE-UP code. in there Read ME filte it was written that you can create other other attacks for which you need to craft poisoned samples and models using this Backdoor box . i want to generate the poisoned dataset and poisoned model

**Comment by zsaba** [comment]
if i have these libraries but with different version. would it work??

**Comment by LandAndLand** [comment]
Hi,

Please refer to [tests/test_SCALE_UP.py](https://github.com/THUYimingLi/BackdoorBox/blob/main/tests/test_SCALE_UP.py), which details how to obtain the poisoned test dataset.

Regarding how to obtain a poisoned model, such as a model poisoned using the BadNets attack, you can train your own poisoned model by following the instructions in [tests/test_BadNets.py](https://github.com/THUYimingLi/BackdoorBox/blob/main/tests/test_BadNets.py).

Hope this helps!

**Comment by zsaba** [comment]
ok. thank you
