### ISSUE TITLE
SCALE-UP、IBD-PSC 链接失效

### ISSUE THREAD

**Issue by lungyam** [THUYimingLi/BackdoorBox#78]

**Comment by lungyam** [comment]
> > 
> 
> 你好，请明确一下issue的具体内容，如哪个文件里的链接失效，以便我们进行检查，更新

这两个论文代码文件失效：
https://github.com/THUYimingLi/BackdoorBox/blob/main/core/defenses/IBD-PSC.py
https://github.com/THUYimingLi/BackdoorBox/blob/main/core/defenses/SCALE-UP.py

**Comment by LandAndLand** [comment]
这个链接意思就是核心代码在本项目下的core/defenses/IBD-PSC.py文件

**Comment by LandAndLand** [comment]
> 这个链接意思就是核心代码在本项目下的core/defenses/IBD-PSC.py文件



> > > 
> > 
> > 
> > 你好，请明确一下issue的具体内容，如哪个文件里的链接失效，以便我们进行检查，更新
> 
> 这两个论文代码文件失效： https://github.com/THUYimingLi/BackdoorBox/blob/main/core/defenses/IBD-PSC.py https://github.com/THUYimingLi/BackdoorBox/blob/main/core/defenses/SCALE-UP.py

这个链接意思就是核心代码在本项目下的core/defenses/IBD-PSC.py文件

**Comment by lungyam** [comment]
> > 这个链接意思就是核心代码在本项目下的core/defenses/IBD-PSC.py文件
> 
> > > > 
> > > 
> > > 
> > > 你好，请明确一下issue的具体内容，如哪个文件里的链接失效，以便我们进行检查，更新
> > 
> > 
> > 这两个论文代码文件失效： https://github.com/THUYimingLi/BackdoorBox/blob/main/core/defenses/IBD-PSC.py https://github.com/THUYimingLi/BackdoorBox/blob/main/core/defenses/SCALE-UP.py
> 
> 这个链接意思就是核心代码在本项目下的core/defenses/IBD-PSC.py文件

感谢您的解答~
