### ISSUE TITLE
运行test_SCALE_UP.py遇到一点问题

### ISSUE THREAD

**Issue by lungyam** [THUYimingLi/BackdoorBox#79]
您好，我运行 test_Wanet.py 获得了 Wanet 中毒模型，在运行 test_SCALE_UP.py 测试防御效果时，加载 wanet 模型遇到了 'netC' 键的缺失问题，打印查看模型键值对时，发现模型似乎没有 'netC' 这个键：
![1](https://github.com/user-attachments/assets/f51a9e21-ed4a-487e-bd46-2c484ab5aa08)
![2](https://github.com/user-attachments/assets/86f07558-f982-4e40-8167-c979e74bb202)

请问是我的处理方式有问题吗？

**Comment by LandAndLand** [comment]
> 您好，我运行 test_Wanet.py 获得了 Wanet 中毒模型，在运行 test_SCALE_UP.py 测试防御效果时，加载 wanet 模型遇到了 'netC' 键的缺失问题，打印查看模型键值对时，发现模型似乎没有 'netC' 这个键： ![1](https://private-user-images.githubusercontent.com/60914339/370730227-f51a9e21-ed4a-487e-bd46-2c484ab5aa08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzQzNDksIm5iZiI6MTcyNzI3NDA0OSwicGF0aCI6Ii82MDkxNDMzOS8zNzA3MzAyMjctZjUxYTllMjEtZWQ0YS00ODdlLWJkNDYtMmM0ODRhYjVhYTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE0MjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWExNWU2MDczZGYyNDc1NmY1OGVjZGNkNmEzNjU0M2VlODA0Yzc4ZTg0YTUwOTU0MDY4YWMxYjE4YWE2NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xTndH_BNl1fMg5BZ8LGTosu40-biVPvjc5K32LOPdaU) ![2](https://private-user-images.githubusercontent.com/60914339/370730268-86f07558-f982-4e40-8167-c979e74bb202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzQzNDksIm5iZiI6MTcyNzI3NDA0OSwicGF0aCI6Ii82MDkxNDMzOS8zNzA3MzAyNjgtODZmMDc1NTgtZjk4Mi00ZTQwLTgxNjctYzk3OWU3NGJiMjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE0MjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MWFmMTM0YThiNzYwN2RhNzY0MmFjYmU5YTUwNWRjNGVmNjZlZjgyYzE3YzkwOTlhZmZiYjg2MmRhY2Q1ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uV48dkJ_mLkLRg2jc3DKHxgH70BAiuSeBiSZj32t0FU)
> 
> 请问是我的处理方式有问题吗？

你好，这个属于是加载模型的问题。因为我在训练模型的时候把模型权重保存在‘netC’关键字中了，所以需要去“netC”里面找模型权重，而你运行test_wanet.py是直接保存模型权重，所以可以用以下方式来加载模型：
model.load_state_dict(torch.load(model_path), strict=False)

**Comment by lungyam** [comment]
> > 您好，我运行 test_Wanet.py 获得了 Wanet 中毒模型，在运行 test_SCALE_UP.py 测试防御效果时，加载 wanet 模型遇到了 'netC' 键的缺失问题，打印查看模型键值对时，发现模型似乎没有 'netC' 这个键： ![1](https://private-user-images.githubusercontent.com/60914339/370730227-f51a9e21-ed4a-487e-bd46-2c484ab5aa08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzQzNDksIm5iZiI6MTcyNzI3NDA0OSwicGF0aCI6Ii82MDkxNDMzOS8zNzA3MzAyMjctZjUxYTllMjEtZWQ0YS00ODdlLWJkNDYtMmM0ODRhYjVhYTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE0MjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ZWExNWU2MDczZGYyNDc1NmY1OGVjZGNkNmEzNjU0M2VlODA0Yzc4ZTg0YTUwOTU0MDY4YWMxYjE4YWE2NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xTndH_BNl1fMg5BZ8LGTosu40-biVPvjc5K32LOPdaU) ![2](https://private-user-images.githubusercontent.com/60914339/370730268-86f07558-f982-4e40-8167-c979e74bb202.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNzQzNDksIm5iZiI6MTcyNzI3NDA0OSwicGF0aCI6Ii82MDkxNDMzOS8zNzA3MzAyNjgtODZmMDc1NTgtZjk4Mi00ZTQwLTgxNjctYzk3OWU3NGJiMjAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE0MjA0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2MWFmMTM0YThiNzYwN2RhNzY0MmFjYmU5YTUwNWRjNGVmNjZlZjgyYzE3YzkwOTlhZmZiYjg2MmRhY2Q1ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uV48dkJ_mLkLRg2jc3DKHxgH70BAiuSeBiSZj32t0FU)
> > 请问是我的处理方式有问题吗？
> 
> 你好，这个属于是加载模型的问题。因为我在训练模型的时候把模型权重保存在‘netC’关键字中了，所以需要去“netC”里面找模型权重，而你运行test_wanet.py是直接保存模型权重，所以可以用以下方式来加载模型： model.load_state_dict(torch.load(model_path), strict=False)

感谢您的解答！！
