### ISSUE TITLE
Blended工具代码问题

### ISSUE THREAD

**Issue by tong-song** [THUYimingLi/BackdoorBox#80]
您好，代码中混合攻击blended代码似乎是badnets攻击，两者代码高度一致，请问是不是弄错了。

**Comment by THUYimingLi** [comment]
> 您好，代码中混合攻击blended代码似乎是badnets攻击，两者代码高度一致，请问是不是弄错了。

Blended是BadNets的一种推广，本质上就是引入了透明度的概念。两者的代码几乎完全相同，你在BadNets中只需要把透明度选用默认的0/1即可，在Blended中可以用0-1
