### ISSUE TITLE
Some doubts about the outcome of the attack

### ISSUE THREAD

**Issue by wxffffff** [THUYimingLi/BackdoorBox#82]
Hello, I found a phenomenon in the training log after running the test_BadNets.py file in the tests folder that makes me wonder, the Top-1 accuracy in "Test result on benign test dataset" is constant at 0.1, and the Top-1 accuracy in "Test result on poisoned test dataset": 1.0, shouldn't the accuracy of "Test result on benign test dataset" be as high as possible, and the accuracy of "Test result on poisoned test dataset" should be as low as possible, if I think correctly, I also got similar results test_BATT.py running, I sincerely hope you can give some suggestions.
![image](https://github.com/user-attachments/assets/6bddc1fd-3179-4670-8eb6-60c5bc264c42)

**Comment by THUYimingLi** [comment]
Hi, thanks for reaching out!

1. Could you please show me your specific running codes? Otherwise, we cannot know what happened.
2. It seems that your current BA is very low (i.e., 0.1/10%) but your ASR is very high (i.e., 1/100%). 
3. You have a misunderstanding. The second line is the ASR instead of the accuracy of poisoned samples on their original label.

**Comment by wxffffff** [comment]
晚上好，不好意思打扰您，我已经上传了运行的代码（就是对backdoorbox中test/test_BadNets.py进行了一些删减，使得他只进行cifar10在resnet18上的训练)和我一次运行过程中的日志,在训练过程中，发现日志内的Top-1 correct / Total: 1000/10000始终没有变过，就有一点困惑，也改过batch_size等参数，但也没有变化。同时，谢谢您对我有关“The second line&nbsp;”的指正。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "THUYimingLi/BackdoorBox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月25日(星期五) 晚上7:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [THUYimingLi/BackdoorBox] Some doubts about the outcome of the attack (Issue #82)





  
Hello, I found a phenomenon in the training log after running the test_BadNets.py file in the tests folder that makes me wonder, the Top-1 accuracy in "Test result on benign test dataset" is constant at 0.1, and the Top-1 accuracy in "Test result on poisoned test dataset": 1.0, shouldn't the accuracy of "Test result on benign test dataset" be as high as possible, and the accuracy of "Test result on poisoned test dataset" should be as low as possible, if I think correctly, I also got similar results test_BATT.py running, I sincerely hope you can give some suggestions. 
  
Hi, thanks for reaching out!
 
Could you please show me your specific running codes? Otherwise, we cannot know what happened.
 It seems that your current BA is very low (i.e., 0.1/10%) but your ASR is very high (i.e., 1/100%).
 You have a misunderstanding. The second line is the ASR instead of the accuracy of poisoned samples on their original label.

**Comment by THUYimingLi** [comment]
> 晚上好，不好意思打扰您，我已经上传了运行的代码（就是对backdoorbox中test/test_BadNets.py进行了一些删减，使得他只进行cifar10在resnet18上的训练)和我一次运行过程中的日志,在训练过程中，发现日志内的Top-1 correct / Total: 1000/10000始终没有变过，就有一点困惑，也改过batch_size等参数，但也没有变化。同时，谢谢您对我有关“The second line&nbsp;”的指正。 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "THUYimingLi/BackdoorBox" ***@***.***&gt;; 发送时间:&nbsp;2024年10月25日(星期五) 晚上7:40 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [THUYimingLi/BackdoorBox] Some doubts about the outcome of the attack (Issue #82) Hello, I found a phenomenon in the training log after running the test_BadNets.py file in the tests folder that makes me wonder, the Top-1 accuracy in "Test result on benign test dataset" is constant at 0.1, and the Top-1 accuracy in "Test result on poisoned test dataset": 1.0, shouldn't the accuracy of "Test result on benign test dataset" be as high as possible, and the accuracy of "Test result on poisoned test dataset" should be as low as possible, if I think correctly, I also got similar results test_BATT.py running, I sincerely hope you can give some suggestions. Hi, thanks for reaching out! Could you please show me your specific running codes? Otherwise, we cannot know what happened. It seems that your current BA is very low (i.e., 0.1/10%) but your ASR is very high (i.e., 1/100%). You have a misunderstanding. The second line is the ASR instead of the accuracy of poisoned samples on their original label. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我好像还是没看到你的codes，上面好像是乱码，你要不再发一遍？

**Comment by THUYimingLi** [comment]
> > 晚上好，不好意思打扰您，我已经上传了运行的代码（就是对backdoorbox中test/test_BadNets.py进行了一些删减，使得他只进行cifar10在resnet18上的训练)和我一次运行过程中的日志,在训练过程中，发现日志内的Top-1 correct / Total: 1000/10000始终没有变过，就有一点困惑，也改过batch_size等参数，但也没有变化。同时，谢谢您对我有关“The second line ”的指正。 ------------------ 原始邮件 ------------------ 发件人: "THUYimingLi/BackdoorBox" _**@**_._**>; 发送时间: 2024年10月25日(星期五) 晚上7:40 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [THUYimingLi/BackdoorBox] Some doubts about the outcome of the attack (Issue #82) Hello, I found a phenomenon in the training log after running the test_BadNets.py file in the tests folder that makes me wonder, the Top-1 accuracy in "Test result on benign test dataset" is constant at 0.1, and the Top-1 accuracy in "Test result on poisoned test dataset": 1.0, shouldn't the accuracy of "Test result on benign test dataset" be as high as possible, and the accuracy of "Test result on poisoned test dataset" should be as low as possible, if I think correctly, I also got similar results test_BATT.py running, I sincerely hope you can give some suggestions. Hi, thanks for reaching out! Could you please show me your specific running codes? Otherwise, we cannot know what happened. It seems that your current BA is very low (i.e., 0.1/10%) but your ASR is very high (i.e., 1/100%). You have a misunderstanding. The second line is the ASR instead of the accuracy of poisoned samples on their original label. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 我好像还是没看到你的codes，上面好像是乱码，你要不再发一遍？

你也可以直接参考我们之前的codes，要是问题解决了你直接关掉issue就行。要是还有问题你可以把更详细的细节放上来哈

链接: https://pan.baidu.com/s/1XTXJzwFQZkHZGRf2bkuuCw 提取码: n07s 
--来自百度网盘超级会员v6的分享

**Comment by wxffffff** [comment]
中午好呀，我又运行了您发来的codes中的test_BadNets.py,训练过程仍然出现了同样的问题，我猜测应该是我的参数设置的不正确，尝试过原参数，以及降低学习率和更改batch_size，但没有效果，我会继续进行尝试，谢谢您的指导。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "THUYimingLi/BackdoorBox"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月25日(星期五) 晚上11:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [THUYimingLi/BackdoorBox] Some doubts about the outcome of the attack (Issue #82)





   
晚上好，不好意思打扰您，我已经上传了运行的代码（就是对backdoorbox中test/test_BadNets.py进行了一些删减，使得他只进行cifar10在resnet18上的训练)和我一次运行过程中的日志,在训练过程中，发现日志内的Top-1 correct / Total: 1000/10000始终没有变过，就有一点困惑，也改过batch_size等参数，但也没有变化。同时，谢谢您对我有关“The second line&nbsp;”的指正。 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "THUYimingLi/BackdoorBox" @.&gt;; 发送时间:&nbsp;2024年10月25日(星期五) 晚上7:40 _@**._&gt;; ***@***.***@._&gt;; 主题:&nbsp;Re: [THUYimingLi/BackdoorBox] Some doubts about the outcome of the attack (Issue #82) Hello, I found a phenomenon in the training log after running the test_BadNets.py file in the tests folder that makes me wonder, the Top-1 accuracy in "Test result on benign test dataset" is constant at 0.1, and the Top-1 accuracy in "Test result on poisoned test dataset": 1.0, shouldn't the accuracy of "Test result on benign test dataset" be as high as possible, and the accuracy of "Test result on poisoned test dataset" should be as low as possible, if I think correctly, I also got similar results test_BATT.py running, I sincerely hope you can give some suggestions. Hi, thanks for reaching out! Could you please show me your specific running codes? Otherwise, we cannot know what happened. It seems that your current BA is very low (i.e., 0.1/10%) but your ASR is very high (i.e., 1/100%). You have a misunderstanding. The second line is the ASR instead of the accuracy of poisoned samples on their original label. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@_.*&gt;
  
我好像还是没看到你的codes，上面好像是乱码，你要不再发一遍？
  
你也可以直接参考我们之前的codes，要是问题解决了你直接关掉issue就行。要是还有问题你可以把更详细的细节放上来哈
 
链接: https://pan.baidu.com/s/1XTXJzwFQZkHZGRf2bkuuCw 提取码: n07s
 --来自百度网盘超级会员v6的分享

**Comment by THUYimingLi** [comment]
> 中午好呀，我又运行了您发来的codes中的test_BadNets.py,训练过程仍然出现了同样的问题，我猜测应该是我的参数设置的不正确，尝试过原参数，以及降低学习率和更改batch_size，但没有效果，我会继续进行尝试，谢谢您的指导。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "THUYimingLi/BackdoorBox" ***@***.***&gt;; 发送时间:&nbsp;2024年10月25日(星期五) 晚上11:37 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [THUYimingLi/BackdoorBox] Some doubts about the outcome of the attack (Issue #82) 晚上好，不好意思打扰您，我已经上传了运行的代码（就是对backdoorbox中test/test_BadNets.py进行了一些删减，使得他只进行cifar10在resnet18上的训练)和我一次运行过程中的日志,在训练过程中，发现日志内的Top-1 correct / Total: 1000/10000始终没有变过，就有一点困惑，也改过batch_size等参数，但也没有变化。同时，谢谢您对我有关“The second line&nbsp;”的指正。 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "THUYimingLi/BackdoorBox" @.&gt;; 发送时间:&nbsp;2024年10月25日(星期五) 晚上7:40 _@**._&gt;; ***@***.***@._&gt;; 主题:&nbsp;Re: [THUYimingLi/BackdoorBox] Some doubts about the outcome of the attack (Issue #82) Hello, I found a phenomenon in the training log after running the test_BadNets.py file in the tests folder that makes me wonder, the Top-1 accuracy in "Test result on benign test dataset" is constant at 0.1, and the Top-1 accuracy in "Test result on poisoned test dataset": 1.0, shouldn't the accuracy of "Test result on benign test dataset" be as high as possible, and the accuracy of "Test result on poisoned test dataset" should be as low as possible, if I think correctly, I also got similar results test_BATT.py running, I sincerely hope you can give some suggestions. Hi, thanks for reaching out! Could you please show me your specific running codes? Otherwise, we cannot know what happened. It seems that your current BA is very low (i.e., 0.1/10%) but your ASR is very high (i.e., 1/100%). You have a misunderstanding. The second line is the ASR instead of the accuracy of poisoned samples on their original label. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@_.*&gt; 我好像还是没看到你的codes，上面好像是乱码，你要不再发一遍？ 你也可以直接参考我们之前的codes，要是问题解决了你直接关掉issue就行。要是还有问题你可以把更详细的细节放上来哈 链接: https://pan.baidu.com/s/1XTXJzwFQZkHZGRf2bkuuCw 提取码: n07s --来自百度网盘超级会员v6的分享 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我觉得你可以先试试直接执行我们的代码，看看能否出现正常的结果。如果可以，就说明可能是你参数或者设置的问题。Otherwise，可能就是codes的配置问题。此外，请注意不要使用多GPU模式，目前多GPU模式好像还是有点问题。

祝好

**Comment by BaCHiiii** [comment]
@THUYimingLi 您好，我也遇到的相同的問題，我是使用您的github中的example.py，但訓練完後的結果就跟上面一樣，如圖。
上圖是train_benign model 下圖是train poison model，dataset的部分是我照著datafolder的方式製作出來的CIFAR10，其他code的部分我沒有做修改，請問可能是什麼原因呢?
![image](https://github.com/user-attachments/assets/6737336f-c17e-4785-b943-c52ef2fb1ba3)
![image](https://github.com/user-attachments/assets/777c7627-20f6-43b1-a3d0-3f1ea5fe8ce8)

**Comment by THUYimingLi** [comment]
> @THUYimingLi 您好，我也遇到的相同的問題，我是使用您的github中的example.py，但訓練完後的結果就跟上面一樣，如圖。 上圖是train_benign model 下圖是train poison model，dataset的部分是我照著datafolder的方式製作出來的CIFAR10，其他code的部分我沒有做修改，請問可能是什麼原因呢? ![image](https://private-user-images.githubusercontent.com/100584575/384695903-6737336f-c17e-4785-b943-c52ef2fb1ba3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDg2ODAsIm5iZiI6MTczMTI0ODM4MCwicGF0aCI6Ii8xMDA1ODQ1NzUvMzg0Njk1OTAzLTY3MzczMzZmLWMxN2UtNDc4NS1iOTQzLWM1MmVmMmZiMWJhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNDE5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOGY5MzMzZmFmYmYyYjI1NjNiZGY0NTljMGIxOWNlZDRkNzBjMWIxZDUzOTZkZDczNzg1ZTM1NzBmNWYyYzUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EMQeRpYk97yD_rS-P7KriS86jzComweEBarR5hp4t7A) ![image](https://private-user-images.githubusercontent.com/100584575/384695972-777c7627-20f6-43b1-a3d0-3f1ea5fe8ce8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNDg2ODAsIm5iZiI6MTczMTI0ODM4MCwicGF0aCI6Ii8xMDA1ODQ1NzUvMzg0Njk1OTcyLTc3N2M3NjI3LTIwZjYtNDNiMS1hM2QwLTNmMWVhNWZlOGNlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNDE5NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTU0ZTQ5YjZhNmMxYzU0ZTEzNmQ4N2E3MmRmZGJhOTdlOWFmZTQ4MzdmNzZmYmFlMTk0MmU3ZDZjZjJmZDg0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4TOvbxmUgsqFzvwGWymMgInTBfGqvwzJQCZReudSh_Q)

请使用test文件夹下的测试文件而非example.py 进行测试 :)

**Comment by BaCHiiii** [comment]
原來是這樣!謝謝您的提醒，我試試看。

**Comment by BaCHiiii** [comment]
您好，剛剛依照您的建議，我在tests中的test.BadNest.py做測試，但窩發現情況還是相同，我原本以為可能是dataset的問題，所以改用torch dataset，但情況還是沒有改變，圖片是原本的設定(我看了code發現其實test_BadNets.py跟example.py沒有很大的改變)，請問可能是什麼原因或是我漏掉了什麼部分嗎?
![螢幕擷取畫面 2024-11-10 231713](https://github.com/user-attachments/assets/72ab98a6-6566-4e2d-9139-822cf5cf6602)
![螢幕擷取畫面 2024-11-10 231859](https://github.com/user-attachments/assets/02b45c80-27ce-4750-aefd-9ec644aee6bb)

**Comment by THUYimingLi** [comment]
> 您好，剛剛依照您的建議，我在tests中的test.BadNest.py做測試，但我發現情況還是相同，我原本以為可能是dataset的問題，所以改用torch dataset，但情況還是沒有改變，圖片是原本的設定(我看了code發現其實test_BadNets.py跟example.py沒有很大的改變)，請問可能是什麼原因或是我漏掉了什麼部分嗎? ![螢幕擷取畫面 2024-11-10 231713](https://private-user-images.githubusercontent.com/100584575/384701013-72ab98a6-6566-4e2d-9139-822cf5cf6602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTI1NDcsIm5iZiI6MTczMTI1MjI0NywicGF0aCI6Ii8xMDA1ODQ1NzUvMzg0NzAxMDEzLTcyYWI5OGE2LTY1NjYtNGUyZC05MTM5LTgyMmNmNWNmNjYwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNTI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmZhNWEwODFlNmFhNDI3ODRlNzc0Y2MzYmMzYWVmNGY2NGJiMDRhM2IzNmFkMWM5ZGVkMzJjZjBhNjdjZDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-Na8oMpX9itcM30AZphayaGAGsxICkttJR4Xr3JZsY8) ![螢幕擷取畫面 2024-11-10 231859](https://private-user-images.githubusercontent.com/100584575/384701017-02b45c80-27ce-4750-aefd-9ec644aee6bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTI1NDcsIm5iZiI6MTczMTI1MjI0NywicGF0aCI6Ii8xMDA1ODQ1NzUvMzg0NzAxMDE3LTAyYjQ1YzgwLTI3Y2UtNDc1MC1hZWZkLTllYzY0NGFlZTZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNTI0MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODBlNWI5MTdjZWIwYjViMTAxY2Q4YTE0MmJmODVmZjE4YWVkMWM3Zjc3MTNiZTM5ZGI5NzllYTBlYzkwZWNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.snthYtOAy5OFXsweVIUxaGPOWAhyFESe5QDdQ4w2pj4)

可能是因为你打开了多卡并行？你试试使用单GPU训练？目前多GPU训练应该会有点问题

**Comment by THUYimingLi** [comment]
> 但是我是用單卡? ![image](https://private-user-images.githubusercontent.com/100584575/384701387-e20392b2-e27f-46c7-9923-de3f1b49c4cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTI3NDcsIm5iZiI6MTczMTI1MjQ0NywicGF0aCI6Ii8xMDA1ODQ1NzUvMzg0NzAxMzg3LWUyMDM5MmIyLWUyN2YtNDZjNy05OTIzLWRlM2YxYjQ5YzRjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNTI3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMGU2OGYzN2RmYjQzMDY1NjgxYzdmNWUwNjM4N2M1YjAxMzA4ZjEyZjU2YTg2MjgwZDYyNzFmYWFkZDliMmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YdWqiA2DSdLdyzy7NCN_RPYaVcSAq4V3IYXtwagiAxI)

我晚点试试，感谢report！

**Comment by BaCHiiii** [comment]
我認為上面的那位先生應該也是這個問題，再麻煩您!

**Comment by BaCHiiii** [comment]
您好，我剛剛右側是了train_benign.py，然後在檢查模型更新的時候，發現模型並沒有做更新，但是有Loss，請問您覺得可能會是哪個部分有出錯呢?
![image](https://github.com/user-attachments/assets/39a20df8-80a9-41dc-974e-15b569f2c897)

**Comment by LandAndLand** [comment]
> 中午好呀，我又运行了您发来的codes中的test_BadNets.py,训练过程仍然出现了同样的问题，我猜测应该是我的参数设置的不正确，尝试过原参数，以及降低学习率和更改batch_size，但没有效果，我会继续进行尝试，谢谢您的指导。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "THUYimingLi/BackdoorBox" ***@***.***&gt;; 发送时间:&nbsp;2024年10月25日(星期五) 晚上11:37 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [THUYimingLi/BackdoorBox] Some doubts about the outcome of the attack (Issue #82) 晚上好，不好意思打扰您，我已经上传了运行的代码（就是对backdoorbox中test/test_BadNets.py进行了一些删减，使得他只进行cifar10在resnet18上的训练)和我一次运行过程中的日志,在训练过程中，发现日志内的Top-1 correct / Total: 1000/10000始终没有变过，就有一点困惑，也改过batch_size等参数，但也没有变化。同时，谢谢您对我有关“The second line&nbsp;”的指正。 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "THUYimingLi/BackdoorBox" @.&gt;; 发送时间:&nbsp;2024年10月25日(星期五) 晚上7:40 _@**._&gt;; ***@***.***@._&gt;; 主题:&nbsp;Re: [THUYimingLi/BackdoorBox] Some doubts about the outcome of the attack (Issue #82) Hello, I found a phenomenon in the training log after running the test_BadNets.py file in the tests folder that makes me wonder, the Top-1 accuracy in "Test result on benign test dataset" is constant at 0.1, and the Top-1 accuracy in "Test result on poisoned test dataset": 1.0, shouldn't the accuracy of "Test result on benign test dataset" be as high as possible, and the accuracy of "Test result on poisoned test dataset" should be as low as possible, if I think correctly, I also got similar results test_BATT.py running, I sincerely hope you can give some suggestions. Hi, thanks for reaching out! Could you please show me your specific running codes? Otherwise, we cannot know what happened. It seems that your current BA is very low (i.e., 0.1/10%) but your ASR is very high (i.e., 1/100%). You have a misunderstanding. The second line is the ASR instead of the accuracy of poisoned samples on their original label. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: _@_.*&gt; 我好像还是没看到你的codes，上面好像是乱码，你要不再发一遍？ 你也可以直接参考我们之前的codes，要是问题解决了你直接关掉issue就行。要是还有问题你可以把更详细的细节放上来哈 链接: https://pan.baidu.com/s/1XTXJzwFQZkHZGRf2bkuuCw 提取码: n07s --来自百度网盘超级会员v6的分享 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，我们把整个repo下载下来，重新测试了一下python tests/test_BadNets.py 文件，下面是我们测试的效果。看起来repo是没有什么问题的。你可以重新下载我们的repo试试，或者你可以检查一下BackdoorBox-main/core/attacks/base.py文件，这里是训练模型的base文件，你看看你在梯度更新那里是否有修改。具体位置大概在base.py文件的第218行左右。
![image](https://github.com/user-attachments/assets/7adf1cb5-3f7f-46f7-8bea-f84af2eb46f5)

**Comment by BaCHiiii** [comment]
你們好，想請教一下你們的python版本是多少?

**Comment by LandAndLand** [comment]
> 你們好，想請教一下你們的python版本是多少?

python3.8

**Comment by BaCHiiii** [comment]
不好意思，雖然我還是沒train起來，但我想問一個比較不相關的問題，為何你們能在test資料夾中的檔案import core而不用加
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
這行code?

**Comment by LandAndLand** [comment]
> 不好意思，雖然我還是沒train起來，但我想問一個比較不相關的問題，為何你們能在tests資料夾中的檔案import core而不用加
> sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
> 這行code?
> 

不好意思 这个我们还没有更新repo 是要加sys.path.append的。我也很疑惑为什么会有问题，你有没有试重新下载repo，配置一下环境，再跑一下？

**Comment by BaCHiiii** [comment]
你們好~ 我成功train起來了!  原因是在linux環境下建置的檔案跟在windows環境下建置的檔案可能有些許不同，所以我原本在windows下訓練不起來，但我嘗試使用docker建立一個linux環境就可以訓練起來了!謝謝你們這幾天提供的協助!
另外requirements.txt應該要新增一個umap
