### ISSUE TITLE
Accuracy Issue with ResNet-18 on CIFAR-10 Using BadNets

### ISSUE THREAD

**Issue by DearYukin** [THUYimingLi/BackdoorBox#83]
Hello, author. I am running test_Badnets.py for ResNet-18_CIFAR-10_BadNets with the following settings: a poisoning rate of 0.1 and training for 200 epochs. However, regardless of the number of epochs, I always get the following output:

==========Test result on benign test dataset==========
[2024-10-26_18:51:41] Top-1 correct / Total: 1000/10000, Top-1 accuracy: 0.1, Top-5 correct / Total: 5000/10000, Top-5 accuracy: 0.5, mean loss: 2.334521770477295, time: 14.033523797988892
==========Test result on poisoned test dataset==========
[2024-10-26_18:51:54] Top-1 correct / Total: 10000/10000, Top-1 accuracy: 1.0, Top-5 correct / Total: 10000/10000, Top-5 accuracy: 1.0, mean loss: 1.6559092998504639, time: 26.63678550720215

I also saw a question in the Issues with the same issue as mine. I ran the code you provided in response to that question, but the results are still the same.I sincerely hope you can point out my mistake.

**Comment by THUYimingLi** [comment]
> Hello, author. I am running test_Badnets.py for ResNet-18_CIFAR-10_BadNets with the following settings: a poisoning rate of 0.1 and training for 200 epochs. However, regardless of the number of epochs, I always get the following output:
> 
> ==========Test result on benign test dataset========== [2024-10-26_18:51:41] Top-1 correct / Total: 1000/10000, Top-1 accuracy: 0.1, Top-5 correct / Total: 5000/10000, Top-5 accuracy: 0.5, mean loss: 2.334521770477295, time: 14.033523797988892 ==========Test result on poisoned test dataset========== [2024-10-26_18:51:54] Top-1 correct / Total: 10000/10000, Top-1 accuracy: 1.0, Top-5 correct / Total: 10000/10000, Top-5 accuracy: 1.0, mean loss: 1.6559092998504639, time: 26.63678550720215
> 
> I also saw a question in the Issues with the same issue as mine. I ran the code you provided in response to that question, but the results are still the same.I sincerely hope you can point out my mistake.

Could you post all your codes here? Otherwise, I cannot know the potential errors more clearly

**Comment by DearYukin** [comment]
> Hello, author. I am running test_Badnets.py for ResNet-18_CIFAR-10_BadNets with the following settings: a poisoning rate of 0.1 and training for 200 epochs. However, regardless of the number of epochs, I always get the following output:
> 
> ==========Test result on benign test dataset========== [2024-10-26_18:51:41] Top-1 correct / Total: 1000/10000, Top-1 accuracy: 0.1, Top-5 correct / Total: 5000/10000, Top-5 accuracy: 0.5, mean loss: 2.334521770477295, time: 14.033523797988892 ==========Test result on poisoned test dataset========== [2024-10-26_18:51:54] Top-1 correct / Total: 10000/10000, Top-1 accuracy: 1.0, Top-5 correct / Total: 10000/10000, Top-5 accuracy: 1.0, mean loss: 1.6559092998504639, time: 26.63678550720215
> 
> I also saw a question in the Issues with the same issue as mine. I ran the code you provided in response to that question, but the results are still the same.I sincerely hope you can point out my mistake.
