### ISSUE TITLE
ISSBA后门攻击没办法获取中毒测试数据集。

### ISSUE THREAD

**Issue by tong-song** [THUYimingLi/BackdoorBox#85]
ISSBA后门攻击类里，
    def get_poisoned_dataset(self):
没办法获取中毒数据集呀，数据中毒代码在训练函数里面糅合，想测试在ISSAB上的防御该怎么获取中毒数据集呢。

**Comment by THUYimingLi** [comment]
> ISSBA后门攻击类里， def get_poisoned_dataset(self): 没办法获取中毒数据集呀，数据中毒代码在训练函数里面糅合，想测试在ISSAB上的防御该怎么获取中毒数据集呢。

请参考 https://github.com/THUYimingLi/BackdoorBox/blob/main/tests/test_ISSBA.py 中的代码，你需要先训练模型再get_poisoned_dataset，因为ISSBA是一种需要操纵训练而非poison-only的后门攻击方法

**Comment by tong-song** [comment]
感觉先训练模型在get_poisoned_dataset还是不太恰当呀，毕竟我测试防御方法时是只想获取中毒数据集，后门模型已经训练好了。难道说每次获取数据集都要重新训练一个ISSBA后门模型吗。老师

**Comment by THUYimingLi** [comment]
> 感觉先训练模型在get_poisoned_dataset还是不太恰当呀，毕竟我测试防御方法时是只想获取中毒数据集，后门模型已经训练好了。难道说每次获取数据集都要重新训练一个ISSBA后门模型吗。老师

你第一次get后存下来到本地即可，下次只需要load就好了

**Comment by tong-song** [comment]
好的，明白了老师，
