### ISSUE TITLE
部分防禦 test result問題

### ISSUE THREAD

**Issue by BaCHiiii** [THUYimingLi/BackdoorBox#86]
我想請問，像是pruning、finetuning這些code目前並沒有顯示做完防禦後模型的ASR對嗎?
還是說我有工具可以使用?
![image](https://github.com/user-attachments/assets/8f551b7f-048a-403b-bf4b-9f04ea738f25)

**Comment by THUYimingLi** [comment]
> 我想請問，像是pruning、finetuning這些code目前並沒有顯示做完防禦後模型的ASR對嗎? 還是說我有工具可以使用? ![image](https://private-user-images.githubusercontent.com/100584575/385868926-8f551b7f-048a-403b-bf4b-9f04ea738f25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5OTk0OTMsIm5iZiI6MTczMTk5OTE5MywicGF0aCI6Ii8xMDA1ODQ1NzUvMzg1ODY4OTI2LThmNTUxYjdmLTA0OGEtNDAzYi1iZjRiLTlmMDRlYTczOGYyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOVQwNjUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjE5M2U2N2U3MTliNTc0ODU0MTJlZjQ1ZDQ3N2MyYzMwMDIzMGFjNjYwYTlhZTgzMzA0MDBiOWNkMDkzMjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XvmyaDK73rONj2FigNfzt9Jv3gnRgJsfGzb0ItTPr1A)

请参考test文件夹下的对应测试文档，对应的工具都在里面了

**Comment by THUYimingLi** [comment]
> 不好意思打擾，請問在utils中的test，其中的 ![image](https://private-user-images.githubusercontent.com/100584575/391702292-b1466d9a-293d-449f-83ba-4fb619a128ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDQ1NzcsIm5iZiI6MTczMzIwNDI3NywicGF0aCI6Ii8xMDA1ODQ1NzUvMzkxNzAyMjkyLWIxNDY2ZDlhLTI5M2QtNDQ5Zi04M2JhLTRmYjYxOWExMjhjYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwNTM3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNWY0MmVmNWFjOTVhMzQ1ZTk3N2JkZTI5NzIwMjIzY2E2OWI5ZDMyYmQyYTJmMjcwMTZjZWYwNGJlZGE3Y2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.s0G7n5Mgpg51wpsnz6O-a44nmO3Te6rkkMzC4u3CBh4) 是什麼意思? 是將不是target label的圖片放入資料集嗎? 我會這樣詢問是因為 我在測試pruning時，對於benign model，他的BA與ASR如下圖 ![image](https://private-user-images.githubusercontent.com/100584575/391704959-ee0447b1-3b6c-4786-86cf-2c36ef95488f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDQ1NzcsIm5iZiI6MTczMzIwNDI3NywicGF0aCI6Ii8xMDA1ODQ1NzUvMzkxNzA0OTU5LWVlMDQ0N2IxLTNiNmMtNDc4Ni04NmNmLTJjMzZlZjk1NDg4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwNTM3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDRjYWU5MzFiZjc2NDNiNTQ2Nzc5MjZiNGFhNjJhNzRjNDVmM2NlMjcyMGIyNDg3M2FhZTk0YmI3MjBlMmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.bhVyVmB_LeXSHr9tLjkFA5iyAKaeBMjurcX9Qcxg5Vo) 為什麼會有攻擊成功率呢? ![image](https://private-user-images.githubusercontent.com/100584575/391705800-d23eff7c-a247-4651-86db-c28636d31707.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMDQ1NzcsIm5iZiI6MTczMzIwNDI3NywicGF0aCI6Ii8xMDA1ODQ1NzUvMzkxNzA1ODAwLWQyM2VmZjdjLWEyNDctNDY1MS04NmRiLWMyODYzNmQzMTcwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwM1QwNTM3NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ODkzN2NhMGUwMDRjMjE5M2I0MGQ4MWJmMjVhMjk0ZGE5MjZjNDY2N2ViNzhmYTMwNTQzZjA3MzRmMjUzMDc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NT2SNPz-gPBf8jL0P0Jj68ZTjXsdNeWJQ4U0RgoPHaE) 如上圖，我的benign model在訓練時是正常的

ASR_nontarget是指去掉目标类别的样本后再计算ASR。这也是为什么你攻击benign model还有ASR的一个很大的原因，因为正常的目标类别的样本也会被分到目标类别。

**Comment by BaCHiiii** [comment]
這個code我理解了，但為什麼在第二張圖，我的benign model的ASR會這麼高?

**Comment by THUYimingLi** [comment]
> 這個code我理解了，但為什麼在第二張圖，我的benign model的ASR會這麼高?

你可以打印一些中间结果来看看，比如预测类别等

**Comment by BaCHiiii** [comment]
好的!那我在研究一下，謝謝!另外，想請問妳們的resner50的label-consistent的GTSRB的訓練的參數是設定多少?，因為我的ASR訓練不起來。

**Comment by THUYimingLi** [comment]
> 好的!那我在研究一下，謝謝!另外，想請問妳們的resner50的label-consistent的GTSRB的訓練的參數是設定多少?，因為我的ASR訓練不起來。

你的目标类别可能需要选成最多的那个类，具体是哪个你可以搜一下。此外，由于方法自身的缺点，LC在类别数量比较多的时候很容易失败。
