### ISSUE TITLE
code for《BAAT: Towards Sample-specific Backdoor Attack with Clean Labels》

### ISSUE THREAD

**Issue by XiaoyuZhou1997** [THUYimingLi/BackdoorBox#87]
请问能否分享论文《BAAT: Towards Sample-specific Backdoor Attack with Clean Labels》(2022,In NeurIPS)的代码

**Comment by THUYimingLi** [comment]
> 请问能否分享论文《BAAT: Towards Sample-specific Backdoor Attack with Clean Labels》(2022,In NeurIPS)的代码

Hi, 目前这篇论文还在期刊审稿中，因此代码还没有开源。另外，之前的那篇是NeurIPS的Workshop而不是正会。
