### ISSUE TITLE
SubImageNet-200数据集模型精度低的问题

### ISSUE THREAD

**Issue by Liu-GuangBin** [THUYimingLi/BackdoorBox#88]
您好！
非常感谢您在后门攻击领域所做的研究工作以及分享代码。我对您发表在ICML2024的《IBD-IPS》这篇论文非常感兴趣，并尝试对其进行了复现。目前，我已经在CIFAR-10和GTSRB数据集上对7种不同的攻击方法训练了后门模型，这些模型均取得了良好的BA（Backdoor Accuracy）和ASR（Attack Success Rate）。

然而，在尝试复现SubImageNet-200数据集上的实验时，我发现所获得的BA并不理想。具体来说，我使用的是发布在Kaggle上的TinyImageNet数据集（链接：[TinyImageNet](https://www.kaggle.com/datasets/nikhilshingadiya/tinyimagenet200)），其图像尺寸为64x64x3，训练样本数为500x200，这与论文中描述的SubImageNet-200的训练样本数量一致。为了匹配模型输入要求，我将图像尺寸调整到了224x224x3。
在实验过程中，我使用了BadNet和IAD两种攻击方法，并选择了ResNet-18、ResNet-101和ResNet-152作为基础模型，进行了400轮次的训练。训练策略包括余弦退火学习率调度和在每100轮将学习率衰减至0.1倍。此外，我还使用了ImageNet数据集的标准化参数（均值：[0.485, 0.456, 0.406]，标准差：[0.229, 0.224, 0.225]）。尽管如此，我得到的最佳BA仅为58%，远低于论文中报告的80%。
因此，我想确认一下，是否是我对SubImageNet-200的理解有误？或者这里提到的SubImageNet-200并非指Kaggle上的TinyImageNet？如果可能的话，能否提供一份您使用的SubImageNet-200数据集，并附带具体的模型配置和训练超参数等详细信息？这将对我进一步的研究提供极大的帮助。
![20241218162623](https://github.com/user-attachments/assets/c3ae1b8d-147b-4b58-a2b6-008e4215e89e)
![20241218162638](https://github.com/user-attachments/assets/66ccf803-1d37-4342-8394-6d52a610a1a8)

**Comment by LandAndLand** [comment]
> 您好！ 非常感谢您在后门攻击领域所做的研究工作以及分享代码。我对您发表在ICML2024的《IBD-IPS》这篇论文非常感兴趣，并尝试对其进行了复现。目前，我已经在CIFAR-10和GTSRB数据集上对7种不同的攻击方法训练了后门模型，这些模型均取得了良好的BA（Backdoor Accuracy）和ASR（Attack Success Rate）。
> 
> 然而，在尝试复现SubImageNet-200数据集上的实验时，我发现所获得的BA并不理想。具体来说，我使用的是发布在Kaggle上的TinyImageNet数据集（链接：[TinyImageNet](https://www.kaggle.com/datasets/nikhilshingadiya/tinyimagenet200)），其图像尺寸为64x64x3，训练样本数为500x200，这与论文中描述的SubImageNet-200的训练样本数量一致。为了匹配模型输入要求，我将图像尺寸调整到了224x224x3。 在实验过程中，我使用了BadNet和IAD两种攻击方法，并选择了ResNet-18、ResNet-101和ResNet-152作为基础模型，进行了400轮次的训练。训练策略包括余弦退火学习率调度和在每100轮将学习率衰减至0.1倍。此外，我还使用了ImageNet数据集的标准化参数（均值：[0.485, 0.456, 0.406]，标准差：[0.229, 0.224, 0.225]）。尽管如此，我得到的最佳BA仅为58%，远低于论文中报告的80%。 因此，我想确认一下，是否是我对SubImageNet-200的理解有误？或者这里提到的SubImageNet-200并非指Kaggle上的TinyImageNet？如果可能的话，能否提供一份您使用的SubImageNet-200数据集，并附带具体的模型配置和训练超参数等详细信息？这将对我进一步的研究提供极大的帮助。 ![20241218162623](https://private-user-images.githubusercontent.com/52373767/396827802-c3ae1b8d-147b-4b58-a2b6-008e4215e89e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjE1NTUsIm5iZiI6MTczNDUyMTI1NSwicGF0aCI6Ii81MjM3Mzc2Ny8zOTY4Mjc4MDItYzNhZTFiOGQtMTQ3Yi00YjU4LWEyYjYtMDA4ZTQyMTVlODllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDExMjczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5NWM4OGQ4YTVhNjY4YzU3ZTlhNWNkZGY3YjYzZWYyOWViZTRjY2JhZGNjZTE4NmU3NDlmYzRmNmNhYjM1MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v6ByKAUZkn179CaBnKXMd9SZgp2dxpBnsLlLlGtGpGw) ![20241218162638](https://private-user-images.githubusercontent.com/52373767/396827827-66ccf803-1d37-4342-8394-6d52a610a1a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjE1NTUsIm5iZiI6MTczNDUyMTI1NSwicGF0aCI6Ii81MjM3Mzc2Ny8zOTY4Mjc4MjctNjZjY2Y4MDMtMWQzNy00MzQyLTgzOTQtNmQ1MmE2MTBhMWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDExMjczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOTU5MWIyNjQyNTE3NGZiYTdiMTM0ZGFlNDQ2MjYxODhmYTkzMGZkYWMzYjNmMzYxOTZiMDZmOWY0Mjk4Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Y8_Muy63_0PjqUSpGhwcK4gQIeSmvz66qydf3Ld0Z-g)

你好，我们已经上传sub-imagenet-200.zip。另外，你可以尝试在预训练好的模型上进行微调，这样BA会高一些。https://drive.google.com/file/d/1s_OunM6elr_0OkSoQK6EpdrzYXs_13QZ/view?usp=drive_link
